const fs = require('fs');

const lines = [
  "import type { Metadata } from 'next';",
  "import Script from 'next/script';",
  "import './globals.css';",
  "import Navbar from '@/components/layout/Navbar';",
  "import Footer from '@/components/layout/Footer';",
  "",
  "export const metadata: Metadata = {",
  "  metadataBase: new URL('https://sdlocalpros.com'),",
  "  title: {",
  "    default: 'San Diego Local Pros | Find Trusted Home Service Professionals',",
  "    template: '%s | San Diego Local Pros',",
  "  },",
  "  description:",
  "    'Find top-rated, licensed home service professionals in San Diego. Compare plumbers, electricians, HVAC contractors, roofers, and more across every neighborhood.',",
  "  keywords: [",
  "    'san diego home services',",
  "    'plumber san diego',",
  "    'electrician san diego',",
  "    'hvac san diego',",
  "    'san diego contractors',",
  "    'local pros san diego',",
  "  ],",
  "  openGraph: {",
  "    type: 'website',",
  "    locale: 'en_US',",
  "    url: 'https://sdlocalpros.com',",
  "    siteName: 'San Diego Local Pros',",
  "    title: 'San Diego Local Pros | Find Trusted Home Service Professionals',",
  "    description:",
  "      'Find top-rated, licensed home service professionals in San Diego. Compare ratings, read reviews, and get free quotes.',",
  "  },",
  "  twitter: {",
  "    card: 'summary_large_image',",
  "    title: 'San Diego Local Pros',",
  "    description: 'Find trusted home service professionals in San Diego.',",
  "  },",
  "  robots: {",
  "    index: true,",
  "    follow: true,",
  "    googleBot: {",
  "      index: true,",
  "      follow: true,",
  "      'max-video-preview': -1,",
  "      'max-image-preview': 'large',",
  "      'max-snippet': -1,",
  "    },",
  "  },",
  "};",
  "",
  "export default function RootLayout({",
  "  children,",
  "}: {",
  "  children: React.ReactNode;",
  "}) {",
  "  return (",
  '    <html lang="en">',
  "      <head>",
  "        <Script",
  '          src="https://www.googletagmanager.com/gtag/js?id=G-P6H81F7W9Z"',
  '          strategy="afterInteractive"',
  "        />",
  '        <Script id="google-analytics" strategy="afterInteractive">',
  "          {`",
  "            window.dataLayer = window.dataLayer || [];",
  "            function gtag(){dataLayer.push(arguments);}",
  "            gtag('js', new Date());",
  "            gtag('config', 'G-P6H81F7W9Z');",
  "          `}",
  "        </Script>",
  '        <Script id="meta-pixel" strategy="afterInteractive">',
  "          {`",
  "            !function(f,b,e,v,n,t,s)",
  "            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?",
  "            n.callMethod.apply(n,arguments):n.queue.push(arguments)};",
  "            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';",
  "            n.queue=[];t=b.createElement(e);t.async=!0;",
  "            t.src=v;s=b.getElementsByTagName(e)[0];",
  "            s.parentNode.insertBefore(t,s)}(window, document,'script',",
  "            'https://connect.facebook.net/en_US/fbevents.js');",
  "            fbq('init', '1567348854472021');",
  "            fbq('track', 'PageView');",
  "          `}",
  "        </Script>",
  "        <noscript>",
  "          <img",
  '            height="1"',
  '            width="1"',
  "            style={{ display: 'none' }}",
  '            src="https://www.facebook.com/tr?id=1567348854472021&ev=PageView&noscript=1"',
  '            alt=""',
  "          />",
  "        </noscript>",
  '        <link rel="icon" href="/favicon.ico" sizes="any" />',
  '        <link rel="preconnect" href="https://fonts.googleapis.com" />',
  "        <link",
  '          rel="preconnect"',
  '          href="https://fonts.gstatic.com"',
  '          crossOrigin="anonymous"',
  "        />",
  "      </head>",
  '      <body className="min-h-screen flex flex-col">',
  "        <Navbar />",
  '        <main className="flex-1">{children}</main>',
  "        <Footer />",
  "      </body>",
  "    </html>",
  "  );",
  "}",
  ""
];

fs.writeFileSync('src/app/layout.tsx', lines.join('\n'));
console.log('layout.tsx written successfully!');